### ISSUE TITLE
Running the contributed command:'...' failed.

### ISSUE THREAD

**Issue by cdxf** [sashaweiss/vscode-bracket-jumper#1]
When the cursor is at the first open bracket, if we use 'ascendLeft' or 'jumpLeft' it will produce follow warning:

> Warn: Running the contributed command:'...' failed.

![bug](https://user-images.githubusercontent.com/6419729/28995150-277e8174-7a0b-11e7-8188-8833a5ad2966.png)

**Comment by sashaweiss** [comment]
Good catch - thanks for the note!

I know this is late, but this is fixed in [the 1.1.7 release](https://github.com/sashaweiss/vscode-bracket-jumper/releases/tag/v1.1.7) that I'm publishing right now!
