### ISSUE TITLE
Change the Shortcut

### ISSUE THREAD

**Issue by renatog-cit** [sashaweiss/vscode-bracket-jumper#7]
Just a little question:

There is a way to change the shortcuts?

The extension is amazing but I have conflicts with other shortcuts. If I can customize it will be amazing!

Thanks Guys!

**Comment by sashaweiss** [comment]
Glad you're enjoying!! Great to hear.

Yes, the shortcuts are very configurable! If you take a look near the middle of the README, there's mention of the following:
```
bracket-jumper.jumpLeft:    { Mac: ctrl+left, Windows/Linux: ctrl+alt+left }
bracket-jumper.jumpRight:   { Mac: ctrl+right, Windows/Linux: ctrl+alt+right }
bracket-jumper.selectLeft:  { Mac: ctrl+shift+left, Windows/Linux: ctrl+alt+shift+left }
bracket-jumper.selectRight: { Mac: ctrl+shift+right, Windows/Linux: ctrl+alt+shift+right }

bracket-jumper.ascendLeft:        { Mac: ctrl+up, Windows/Linux: ctrl+alt+up }
bracket-jumper.ascendRight:       { Mac: ctrl+down, Windows/Linux: ctrl+alt+down }
bracket-jumper.selectAscendLeft:  { Mac: ctrl+shift+up, Windows/Linux: ctrl+alt+shift+up }
bracket-jumper.selectAscendRight: { Mac: ctrl+shift+down, Windows/Linux: ctrl+alt+shift+down }
```
Those are the default shortcuts installed with the extension, but in your own [keybindings.json](https://code.visualstudio.com/docs/getstarted/keybindings) you can override those to be whatever you'd like.

Please reopen and/or let me know if you have any further issues!

**Comment by renatog-cit** [comment]
Yeah!  Really works good!!

Thank you very much, man!

Best,
